{% set tests_to_skip = "_not_a_real_test" %}
{% set version = "3.13.0" %}

package:
  name: aiohttp
  version: {{ version }}

source:
  - url: https://files.pythonhosted.org/packages/62/f1/8515650ac3121a9e55c7b217c60e7fae3e0134b5acfe65691781b5356929/aiohttp-{{ version }}.tar.gz
    sha256: 378dbc57dd8cf341ce243f13fa1fa5394d68e2e02c15cd5f28eae35a70ec7f67
  # download sources to have tests, which don't get installed;
  # installing from source is very painful, beware...
  - url: https://github.com/aio-libs/aiohttp/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7a3398198d60c14ec060868ae6c1ede55833b67af728733d76944293a5b6e071
    folder: sources

build:
  number: 0
  noarch: python  # [use_noarch]
  track_features:
    - aiohttp_no_compile    # [use_noarch]
  script:
    - export AIOHTTP_NO_EXTENSIONS=1      # [use_noarch]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [not use_noarch and build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [not use_noarch and build_platform != target_platform]
    - cython                                 # [not use_noarch and build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python                   # [not use_noarch]
    - python {{ python_min }}  # [use_noarch]
    - pip
    - cython
    - pkgconfig
    - setuptools >=46.4.0
  run:
    - python                     # [not use_noarch]
    - python >={{ python_min }}  # [use_noarch]
    - aiohappyeyeballs >=2.5.0
    - aiosignal >=1.4.0
    - async-timeout >=4.0,<6.0   # [py<311 or use_noarch]
    - attrs >=17.3.0
    - frozenlist >=1.1.1
    - multidict >=4.5,<7.0
    - propcache >=0.2.0
    - yarl >=1.17.0,<2.0

test:
  requires:
    - python                   # [not use_noarch]
    - python {{ python_min }}  # [use_noarch]
    - pip
    - pytest <8
    - pytest-mock
    - pytest-codspeed
    - python-blockbuster
    - brotli
    - brotlicffi
    - freezegun
    - python-isal
    - gunicorn    # [unix]
    - pkgconfig
    - proxy-py
    - re-assert
    - time-machine  # [python_impl == "cpython"]
    - trustme
    - uvloop  # [unix]
    - python-zlib-ng
  source_files:
    - sources/tests
    # used by a test
    - sources/README.rst
  imports:
    - aiohttp
  commands:
    - pip check
    - export AIOHTTP_NO_EXTENSIONS=1      # [use_noarch]
    # don't want the docker tests in the autobahn subfolder
    - rm -rf sources/tests/autobahn         # [unix]
    - rmdir /s /q sources\tests\autobahn    # [win]
    {% set tests_to_skip = "_not_a_real_test" %}
    # Doesn't reliably run fast enough in CI
    {% set tests_to_skip = tests_to_skip + " or test_import_time" %}
    # Fails since 270ae9cf6a9e6159b5e29a950deb6ff7600aebc5
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_strict_obs_line_folding" %}
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_bad_chunked_strict_c[pyloop]" %}
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_bad_chunked_strict_py[pyloop]" %}
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_strict_headers[c-parser-pyloop]" %}
    {% set tests_to_skip = tests_to_skip + " or test_tcp_connector_raise_connector_ssl_error[pyloop]" %}
    # flaky tests
    {% set tests_to_skip = tests_to_skip + " or test_heartbeat_no_pong[pyloop]" %}
    # test failing with python >=3.11
    {% set tests_to_skip = tests_to_skip + " or test_https_proxy_unsupported_tls_in_tls[pyloop-https]" %}   # [py>=311]
    # fails to open socket at desired IP/port
    {% set tests_to_skip = tests_to_skip + " or (test_web_server and test_handler_cancellation)" %}         # [linux]
    {% set tests_to_skip = tests_to_skip + " or (test_web_server and test_no_handler_cancellation)" %}      # [linux]
    {% set tests_to_skip = tests_to_skip + " or test_run_app_preexisting_inet6_socket[pyloop]" %}           # [linux]
    # emulation is too slow for expected speed
    {% set tests_to_skip = tests_to_skip + " or (test_imports and test_import_time)" %}                     # [aarch64 or ppc64le]
    # test is failing with 505 instead of 404 for Windows and python 3.9
    {% set tests_to_skip = tests_to_skip + " or (test_access_symlink_loop[pyloop] )" %}                     # [win and py<=39]
    - pytest sources/tests/ -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/aio-libs/aiohttp
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE.txt
    - vendor/llhttp/LICENSE
  license_family: Apache
  summary: Async http client/server framework (asyncio)

  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
    - ocefpaf
    - xylar
