{% set tests_to_skip = "_not_a_real_test" %}
{% set version = "3.9.4" %}

package:
  name: aiohttp
  version: {{ version }}

source:
  - url: https://github.com/aio-libs/aiohttp/archive/a459459bbf502eafd12d66903327376fa15dcf0f.tar.gz
    sha256: d26c06b72d868ebd0ce8d4d65d71102d06899c21d3d100ec351866d4d7863122
  - url: https://github.com/nodejs/llhttp/archive/533845688d173561b9cba33269130401add38567.tar.gz
    sha256: 38ad4f91f8ab7a60a15ea569142c1f83a3b85232b82bbdb3e0b48cdf9e11ad90
    folder: vendor/llhttp

build:
  number: 1
  skip: true  # [win]
  script:
    - pushd vendor/llhttp
    - npm ci
    - make generate
    - popd
    - git init
    - git submodule update --init --recursive
    - make aiohttp/_find_header.c
    - for i in $(find aiohttp -name '*.pyx'); do make ${i/.pyx/.c}; done
    - rm -r .git
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
    - cython
    - multidict
  run:
    - python
    - aiosignal >=1.1.2
    - async-timeout >=4.0,<5.0  # [py<311]
    - attrs >=17.3.0
    - frozenlist >=1.1.1
    - multidict >=4.5,<7.0
    - yarl >=1.0,<2.0

test:
  requires:
    - pip
    - pytest <8
    - pytest-mock
    - brotli
    - brotlicffi
    - freezegun
    - gunicorn    # [unix]
    - proxy-py
    - re-assert
    - time-machine  # [python_impl == "cpython"]
    - trustme
  source_files:
    - tests
    # used by a test
    - README.rst
  imports:
    - aiohttp
  commands:
    - pip check
    # don't want the docker tests in the autobahn subfolder
    - rm -rf tests/autobahn         # [unix]
    - rmdir /s /q tests\autobahn    # [win]
    {% set tests_to_skip = "_not_a_real_test" %}
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_bad_chunked_strict_c[pyloop]" %}
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_bad_chunked_strict_py[pyloop]" %}
    {% set tests_to_skip = tests_to_skip + " or test_http_response_parser_strict_headers[c-parser-pyloop]" %}
    {% set tests_to_skip = tests_to_skip + " or test_tcp_connector_raise_connector_ssl_error[pyloop]" %}
    # flaky tests
    {% set tests_to_skip = tests_to_skip + " or test_heartbeat_no_pong[pyloop]" %}
    # test failing with python >=3.11
    {% set tests_to_skip = tests_to_skip + " or test_https_proxy_unsupported_tls_in_tls[pyloop-https]" %}   # [py>=311]
    # fails to open socket at desired IP/port
    {% set tests_to_skip = tests_to_skip + " or (test_web_server and test_handler_cancellation)" %}         # [linux]
    {% set tests_to_skip = tests_to_skip + " or (test_web_server and test_no_handler_cancellation)" %}      # [linux]
    {% set tests_to_skip = tests_to_skip + " or test_run_app_preexisting_inet6_socket[pyloop]" %}           # [linux]
    # emulation is too slow for expected speed
    {% set tests_to_skip = tests_to_skip + " or (test_imports and test_import_time)" %}                     # [aarch64 or ppc64le]
    # aio seems to hard-code expectation for cpython (i.e. not "pypy3.9" in SP_DIR path)
    {% set tests_to_skip = tests_to_skip + " or test_static_route_user_home" %}             # [python_impl == "pypy"]
    # not working with pypy (all platforms)
    {% set tests_to_skip = tests_to_skip + " or test_c_parser_loaded" %}                    # [python_impl == "pypy"]
    {% set tests_to_skip = tests_to_skip + " or test_invalid_character[pyloop]" %}          # [python_impl == "pypy"]
    {% set tests_to_skip = tests_to_skip + " or test_invalid_linebreak[pyloop]" %}          # [python_impl == "pypy"]
    # not working with pypy (win)
    {% set tests_to_skip = tests_to_skip + " or test_access_to_the_file_with_spaces" %}     # [python_impl == "pypy" and win]
    {% set tests_to_skip = tests_to_skip + " or test_follow_symlink[pyloop]" %}             # [python_impl == "pypy" and win]
    {% set tests_to_skip = tests_to_skip + " or test_static_file_huge[pyloop] " %}          # [python_impl == "pypy" and win]
    {% set tests_to_skip = tests_to_skip + " or test_subapp_reverse_static_url[pyloop]" %}  # [python_impl == "pypy" and win]
    {% set tests_to_skip = tests_to_skip + " or test_unsupported_upgrade[pyloop] " %}       # [python_impl == "pypy" and win]
    - pytest tests/ -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/aio-libs/aiohttp
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE.txt
    - vendor/llhttp/LICENSE-MIT
  license_family: Apache
  summary: Async http client/server framework (asyncio)

  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
    - ocefpaf
