{% set name = "aiohttp" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3b19d8d183bcfd68b25beebab8dc3308282fe2ca3d6ea3cb4cd101b3c279f8d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - async-timeout >=3.0,<4.0
    - attrs >=17.3.0
    - chardet >=2.0,<5.0
    - idna_ssl >=1.0  # [py<37]
    - multidict >=4.5,<7.0
    - typing-extensions >=3.6.5
    - yarl >=1.0,<2.0

test:
  imports:
    - aiohttp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiohttp
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: Async http client/server framework (asyncio)

  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
    - ocefpaf
