{% set name = "aiohttp" %}
{% set version = "3.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 698cd7bc3c7d1b82bb728bae835724a486a8c376647aec336aa21a60113c3645

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - attrs >=17.3.0
    - chardet >=2.0,<4.0
    - multidict >=4.5,<5.0
    - async-timeout >=3.0,<4.0
    - yarl >=1.0,<2.0
    - idna_ssl >=1,<2  # [py<37]
    - typing_extensions >=3.6.5  # [py<37]

test:
  imports:
    - aiohttp

about:
  home: https://github.com/aio-libs/aiohttp
  license: Apache 2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: Async http client/server framework (asyncio)

  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
