{% set version = "3.8.6" %}

package:
  name: aiohttp
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/a/aiohttp/aiohttp-{{ version }}.tar.gz
    sha256: b0cf2a4501bff9330a8a5248b4ce951851e415bdcce9dc158e76cfd55e15085c
  # download sources to have tests, which don't get installed;
  # installing from source is very painful, beware...
  - url: https://github.com/aio-libs/aiohttp/archive/refs/tags/v{{ version }}.tar.gz
    sha256: f437a7a676ee59f933a3592e3777690110bc570b38f702192bf349805382c22d
    folder: sources

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - aiosignal >=1.1.2
    - async-timeout <5.0,>=4.0.0a3
    - attrs >=17.3.0
    - charset-normalizer >=2.0,<4.0
    - frozenlist >=1.1.1
    - multidict >=4.5,<7.0
    - yarl >=1.0,<2.0

test:
  requires:
    - pip
    - pytest
    - pytest-mock
    - brotli
    - brotlicffi
    - freezegun
    - proxy-py
    - re-assert
    - trustme
  source_files:
    - sources/tests
    # used by a test
    - sources/README.rst
  imports:
    - aiohttp
  commands:
    - pip check
    # don't want the docker tests in the autobahn subfolder
    - rm -rf sources/tests/autobahn         # [unix]
    - rmdir /s /q sources\tests\autobahn    # [win]
    - pytest sources/tests/

about:
  home: https://github.com/aio-libs/aiohttp
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE.txt
    - vendor/llhttp/LICENSE-MIT
  license_family: Apache
  summary: Async http client/server framework (asyncio)

  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - xhochy
    - ocefpaf
