appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RBM8evCykUAIIS3Ocod5U1b+xueq3An0P9cJv6QSW9yWt7lK9I03GdyLw7eHP4J9YTfOzHOOkXd8jCzFw+6HOwu5nEnd0QFi2eOW/K2+fSjet4i3Yr0xdR3yd0KEtkHF+ml/mUnZVfkfDeKmk+CUjCpSAAUyn+4m5HPvCP6rtLdcC/NAB9e+vUPD4zWg8fCNTWRQ7fij7NarzzV3eiWk6MH5bY6YMWFe9SC+PXUxnuGfIzjy85uifW1P9WKO2WfW06afzpErkSI/PWa94ULlhyniK7+VAh7ThntKeKY6NbMAbIfx5vdJwDFai1TklRbaSMMvyfRlPlkQV/9a7nGoZRBEzSTS80icJPXOBg9ghdBsUaFGHXy7VKAA3oh4MDk0l1oJlfypelxoe5MUHpN5KGBnQZQd5NJzdr7WCTdVm7IdDSwRU6i0+tkJQRvJKD6W8VbS4NJ6SARISkxhrSvwwKnypnzFQPOzFCsJR4SjYpDhlYw+0/Uh0VhkNiBHSHGL5szvqVZUie1znKQp6zDE7bHJ4vz3Txus/pWvUMVHd1O73jOayraYpzTsgnKMnMmKogbOaijEscDfmE5MfkExSfIFvGv9KbH0u5le6zC+tyjYo7MwiazJgp+COSxzyM2UYcR6vlQ9O9qfn2cWvKOT1vy2QiHbmnL8JHygHtISk0k=}
